print("##############################")
print("#                            #")
print("#     Rahma Syarita Jaya     #")
print("#        2510817320004       #")
print("#                            #")
print("##############################")